FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
MAINTAINER Chen Fei <chenfei@virtaitech.com>

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    rm /etc/apt/sources.list.d/*

RUN apt-get update -y &&\
    apt install -y iproute2 &&\
    apt install -y librdmacm1 libibverbs1 &&\
    apt install -y wget bc net-tools &&\
    apt install -y lsb-core &&\
    apt install -y vim &&\
    apt install -y libcurl4-openssl-dev

# Install RDMA driver
WORKDIR /tmp

RUN wget http://content.mellanox.com/ofed/MLNX_OFED-4.5-1.0.1.0/MLNX_OFED_LINUX-4.5-1.0.1.0-ubuntu16.04-x86_64.tgz

RUN tar xvf MLNX_OFED_LINUX-4.5-1.0.1.0-ubuntu16.04-x86_64.tgz &&\
    cd MLNX_OFED_LINUX-4.5-1.0.1.0-ubuntu16.04-x86_64 &&\
    ./mlnxofedinstall --user-space-only --without-fw-update --all --force -q &&\
    cd /tmp && rm -rf *

RUN apt clean

COPY entrypoint.sh  /entrypoint.sh
RUN chmod +x        /entrypoint.sh

COPY oriond         /usr/bin/oriond
RUN chmod +x        /usr/bin/oriond

WORKDIR /root
CMD ["/entrypoint.sh"]
